name: CI - Integración Continua
on:
  push:
    branches: [dev]

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "Pulling [dev] ${{ github.ref }} into [main]. AutoPR" # Title of pull request
          pr_body: ":crown: *An automated PR*. Developer Team: @nubezartech/internaldevs."
          pr_reviewer: "aabadmo4"
          github_token: ${{ secrets.ORG_GITHUB_ACCES_TOKEN }}
      - uses: fjogeleit/http-request-action@v1
      - name: Deploy Stage
        with:
          url: ${{ secrets.TW_MAKE_SMS_URL_POST_JSON }}
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"receiver": "+34643042261", "msg": "[- $GITHUB_REPOSITORY -]  Pulling [dev] ${{ github.ref }} into [main]. ${{steps.open-pr.outputs.pr_url}}"}'